# Generated by Django 5.2.13 on 2026-04-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('cnic', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('rickshaw', 'Rickshaw')], max_length=20)),
                ('vehicle_make_model', models.CharField(max_length=120)),
                ('vehicle_year', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('active', 'Active')], default='pending', max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='registratio_created_52644e_idx'), models.Index(fields=['city'], name='registratio_city_30242a_idx'), models.Index(fields=['vehicle_type'], name='registratio_vehicle_6429f1_idx'), models.Index(fields=['status'], name='registratio_status_fb73b3_idx'), models.Index(fields=['phone'], name='registratio_phone_1b7f5b_idx')],
            },
        ),
    ]
