# Generated by Django 5.2.13 on 2026-04-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('rickshaw', 'Rickshaw')], max_length=20)),
                ('trip_target', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'city', 'vehicle_type'],
                'indexes': [models.Index(fields=['city', 'vehicle_type'], name='public_cont_city_b902e9_idx'), models.Index(fields=['is_active', 'sort_order'], name='public_cont_is_acti_ed065a_idx')],
                'unique_together': {('city', 'vehicle_type', 'trip_target')},
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='public_cont_is_acti_ded9bf_idx'), models.Index(fields=['start_date', 'end_date'], name='public_cont_start_d_aec1c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promo-banners/')),
                ('cta_label', models.CharField(blank=True, max_length=60)),
                ('cta_url', models.URLField(blank=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='public_cont_is_acti_49290e_idx')],
            },
        ),
        migrations.CreateModel(
            name='TripBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('rickshaw', 'Rickshaw')], max_length=20)),
                ('trip_target', models.PositiveIntegerField()),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'city', 'vehicle_type', 'trip_target'],
                'indexes': [models.Index(fields=['city', 'vehicle_type'], name='public_cont_city_0bee4a_idx'), models.Index(fields=['is_active', 'sort_order'], name='public_cont_is_acti_5d1ca9_idx')],
                'unique_together': {('city', 'vehicle_type', 'trip_target', 'bonus_amount')},
            },
        ),
    ]
