# Generated by Django 5.2.13 on 2026-04-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityGoal',
        ),
        migrations.DeleteModel(
            name='PromoBanner',
        ),
    ]
